version: '3.5'
services:
  postgres:
  # /usr/lib/postgresql/12/bin/pg_upgrade --old-datadir=/var/lib/postgresql/10/main --new-datadir=/var/lib/postgresql/12/main --old-bindir=/usr/lib/postgresql/10/bin --new-bindir=/usr/lib/postgresql/12/bin --old-options '-c config_file=/etc/postgresql/10/main/postgresql.conf' --new-options '-c config_file=/etc/postgresql/12/main/postgresql.conf'
    restart: always
    image: postgis/postgis:15-3.3-alpine
    environment:
      POSTGRES_PASSWORD: gst3
      POSTGRES_USER: gst3
      PGDATA: /var/lib/postgresql/data/pgdata
    stop_grace_period: 120s
    networks:
      internal:
        aliases:
          - postgres
        ipv4_address: 192.168.7.2
    volumes:
      - "pgdata:/var/lib/postgresql/data/pgdata"
  apache:
    restart: "always"
    build:
      context: webserver
      dockerfile: Dockerfile
      args:
       - ACTIVATE_SSL=true
    environment:
      WEB_PHP_SOCKET: "192.168.7.3:9000"
      WEB_DOCUMENT_ROOT: "/usr/GiGa/gstws/public/"
      WEB_ALIAS_DOMAIN: "nagra-dev.giga-infosystems.com"
      WEB_DOCUMENT_INDEX: "index.php"
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - "webroot:/usr/GiGa/gstws/"
      - "internalssl:/usr/GiGa/gstws/public/sslcert"
      - "letsencrypt:/etc/letsencrypt"
      - "logs:/var/log/apache2"
      - "stats:/var/lib/awstats"
      # geoplasma stuff
      - "VOLUME:/var/www/html/backend"
      - "VOLUME:/var/www/html/frontend"
      - "VOLUME:/var/www/html/content"
    networks:
      internal:
        aliases:
          - apache
        ipv4_address: 192.168.7.4
  gst-server:
    user: "101:101"
    ports:
      - "50052:50051"
    build:
      context: gst-server
      dockerfile: Dockerfile
    volumes:
      - "internalssl:/etc/GiGa/ssl"
      - /etc/GiGa/license:/etc/GiGa/license
      - "gstdata:/data"
    restart: 'always'
    networks:
      internal:
        aliases:
          - gst
        ipv4_address: 192.168.7.5
  geoserver:
    ports:
      - "8080:8080"
    image: docker.osgeo.org/geoserver:2.23.1
    environment:
      -  SKIP_DEMO_DATA=true
    volumes:
      - "gstdata:/data"
    restart: 'always'
    networks:
      internal:
        aliases:
          - geoserver
        ipv4_address: 192.168.7.6

volumes:
  webroot:
  internalssl:
  pgdata:
  gstdata:
  letsencrypt:
  logs:
  stats:
  VOLUME:

networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: 192.168.7.0/24
