version: '3.5'
services:
  postgres:
    restart: always
    image: postgis/postgis:14-3.3-alpine
    environment:
      POSTGRES_PASSWORD: gst
      POSTGRES_USER: gst
      PGDATA: /var/lib/postgresql/data/pgdata
    stop_grace_period: 120s
    networks:
      internal:
        aliases:
          - postgres
        ipv4_address: 192.168.7.2
    volumes:
      #- "/home/adminplasma/var/geoplasma/new-data:/var/lib/postgresql/data/"
      - "pgdata:/var/lib/postgresql/data/"
  apache:
    restart: "always"
    build:
      context: webserver
      dockerfile: Dockerfile
      args:
       - ACTIVATE_SSL=true
    environment:
      WEB_DOCUMENT_ROOT: "/home/adminplasma/var/geoplasma/geoplasma/"
      WEB_ALIAS_DOMAIN: "portal.geoplasma-ce.eu"
      WEB_DOCUMENT_INDEX: "index.php"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "internalssl:/etc/GiGa/ssl"
      - "/home/adminplasma/var/geoplasma/geoplasma/letsencrypt:/etc/letsencrypt"
      - "logs:/var/log/apache2"
      - "stats:/var/lib/awstats"
      # geoplasma stuff
      - "/home/adminplasma/var/geoplasma/geoplasma/backend:/var/www/html/backend"
      - "/home/adminplasma/var/geoplasma/geoplasma/frontend:/var/www/html/frontend"
      - "/home/adminplasma/var/geoplasma/uploadContent:/var/www/html/content"
    networks:
      internal:
        aliases:
          - apache
          - portal.geoplasma-ce.eu
          - api.geoplasma-ce.eu
          - downloads.geoplasma-ce.eu
        ipv4_address: 192.168.7.4
  gst-server:
    #ports:
    #  - "50052:50051"
    build:
      context: gst-server
      dockerfile: Dockerfile
    volumes:
      - "internalssl:/etc/GiGa/ssl"
      - /home/adminplasma/var/geoplasma/license:/etc/GiGa/license
      - "/home/adminplasma/var/geoplasma/gstdata:/var/lib/gstdata/"
    restart: 'always'
    networks:
      internal:
        aliases:
          - gst
        ipv4_address: 192.168.7.5
  geoserver:
    #ports:
    #  - "8080:8080"
    image: docker.osgeo.org/geoserver:2.23.1
    environment:
      -  SKIP_DEMO_DATA=true
    volumes:
      - "/home/adminplasma/var/geoplasma/geoserver_data:/opt/geoserver_data/"
    restart: 'always'
    networks:
      internal:
        aliases:
          - geoserver
        ipv4_address: 192.168.7.6

volumes:
  webroot:
  internalssl:
  pgdata:
  gstdata:
  letsencrypt:
  logs:
  stats:

networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: 192.168.7.0/24
